<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>BabyNii💌</title>

<!-- Font đáng yêu -->
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@600&display=swap" rel="stylesheet">

<style>
  body {
    background-color: #ffe6f2;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
    font-family: 'Poppins', sans-serif;
    overflow: hidden;
  }

  .envelope {
    position: relative;
    width: 420px;
    height: 280px;
    background: #ffb6c1;
    border-radius: 25px;
    box-shadow: 0 0 40px rgba(255, 182, 193, 0.7);
    cursor: pointer;
    perspective: 1000px;
    transition: transform 0.6s ease;
  }

  /* nắp phong bì */
  .flap {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 55%;
    background: #ffc0cb;
    border-top-left-radius: 25px;
    border-top-right-radius: 25px;
    border-bottom-left-radius: 40% 40%;
    border-bottom-right-radius: 40% 40%;
    transform-origin: top;
    transition: transform 1s ease;
    z-index: 2;
  }

  /* chữ "Gửi tặng chị 💌" bên trong nắp */
  .flap-text {
    position: absolute;
    top: 50%; /* chỉnh lại vị trí để thật giữa nắp */
    left: 50%;
    transform: translate(-50%, -50%) rotateX(180deg);
    font-family: 'Dancing Script', cursive;
    font-size: 40px;
    color: #e75480;
    font-weight: 600;
    opacity: 0;
    transition: opacity 1s ease;
    text-shadow: 0 0 10px #ff99b9, 0 0 20px #fff;
    text-align: center;
    white-space: nowrap;
  }

  /* hiệu ứng chữ nhấp nháy nhẹ */
  @keyframes textGlow {
    0%, 100% { opacity: 1; text-shadow: 0 0 10px #ff99b9, 0 0 20px #fff; }
    50% { opacity: 0.7; text-shadow: 0 0 15px #ff4d6d, 0 0 30px #fff; }
  }

  .seal {
    position: absolute;
    top: 55%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 110px;
    height: 110px;
    background-color: #e75480;
    border-radius: 50%;
    box-shadow: 0 0 25px rgba(231, 84, 128, 0.8);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 50px;
    color: white;
    user-select: none;
    z-index: 3;
    transition: opacity 0.6s ease;
  }

  .heart {
    position: absolute;
    top: 52%;
    left: 50%;
    transform: translate(-50%, -50%) scale(0);
    font-size: 130px;
    opacity: 0;
    z-index: 1;
    transition: all 0.8s ease;
    filter: drop-shadow(0 0 8px red);
  }

  /* Hiệu ứng phát sáng, nhấp nháy nhẹ */
  @keyframes sparkle {
    0% {
      filter: drop-shadow(0 0 8px #ff4d6d)
              drop-shadow(0 0 15px #ff8095)
              drop-shadow(0 0 20px white);
      transform: translate(-50%, -50%) scale(1.25);
    }
    50% {
      filter: drop-shadow(0 0 20px #ff1e56)
              drop-shadow(0 0 35px #ffc0cb)
              drop-shadow(0 0 45px white);
      transform: translate(-50%, -50%) scale(1.3);
    }
    100% {
      filter: drop-shadow(0 0 10px #ff4d6d)
              drop-shadow(0 0 25px #ff99b9)
              drop-shadow(0 0 40px white);
      transform: translate(-50%, -50%) scale(1.25);
    }
  }

  @keyframes shake {
    0%, 100% { transform: translate(0, 0) rotate(0deg); }
    20% { transform: translate(-3px, 2px) rotate(-2deg); }
    40% { transform: translate(3px, -2px) rotate(2deg); }
    60% { transform: translate(-2px, 2px) rotate(-1deg); }
    80% { transform: translate(2px, -2px) rotate(1deg); }
  }

  .shake {
    animation: shake 0.4s ease;
  }

  .open .flap {
    transform: rotateX(180deg);
  }

  .open .seal {
    opacity: 0;
  }

  .open .flap-text {
    opacity: 1;
    animation: textGlow 2s infinite ease-in-out;
  }

  .open .heart {
    opacity: 1;
    transform: translate(-50%, -50%) scale(1.25);
    animation: sparkle 1.2s infinite ease-in-out;
  }
</style>
</head>
<body>
  <div class="envelope" id="envelope">
    <div class="flap">
      <div class="flap-text">Gửi tặng chị</div>
    </div>
    <div class="seal">💌</div>
    <div class="heart" id="heart">❤️</div>
  </div>

  <script>
    const envelope = document.getElementById('envelope');
    const seal = envelope.querySelector('.seal');

    seal.addEventListener('click', () => {
      envelope.classList.add('shake');
      setTimeout(() => {
        envelope.classList.remove('shake');
        envelope.classList.toggle('open');
      }, 400);
    });
  </script>
</body>
</html>
